import 'native/prism_ffi.dart';

// ─────────────────────────────────────────────────────────────
// SEALED BYTES — Dart-side façade over the Rust codec
// ─────────────────────────────────────────────────────────────
// Every value that would otherwise ship as a Dart string literal
// (ruling endpoint, AppsFlyer dev key, Firebase project, UA
// scaffolding fragments, WebView JS payloads) now lives inside
// `libprism_core.so`. This module is a thin façade so the
// call sites in the rest of the project do not need to change.
//
// Call-site contract (unchanged from the previous Dart-only
// codec): every accessor returns the plaintext string, or `""`
// when the Rust library is not loadable (desktop host, missing
// `.so`, loader failure). Call sites branch on `.isEmpty` and
// fall back to the native-game path.
//
// Historical notes:
//   • The sealed byte arrays used to live here as `const List<int>`
//     literals. They were generated by `tool/prism_pack.dart`
//     via the Dart codec in `cloak.dart`. Both the generator
//     and the Dart codec still work — the generator just prints
//     byte lists you paste into `rust/prism_core/src/sealed.rs`
//     (instead of this file).
//   • Static scanners that `grep` the compiled Dart snapshot
//     (`libapp.so`) for AppsFlyer / Firebase / `luminafortune`
//     strings now miss everything — the plaintext is produced
//     on demand by the Rust side and never sits in a Dart
//     string literal.
// ─────────────────────────────────────────────────────────────

String unsealEndpoint() => PrismNative.read(SealedIndex.endpoint);
String unsealGcdBase() => PrismNative.read(SealedIndex.gcdBase);
String unsealAttributionKey() =>
    PrismNative.read(SealedIndex.attributionKey);
String unsealMessagingProject() =>
    PrismNative.read(SealedIndex.messagingProject);

String unsealUaProduct() => PrismNative.read(SealedIndex.uaProduct);
String unsealUaLinuxOpen() => PrismNative.read(SealedIndex.uaLinuxOpen);
String unsealUaBuildLabel() => PrismNative.read(SealedIndex.uaBuildLabel);
String unsealUaBuildClose() => PrismNative.read(SealedIndex.uaBuildClose);
String unsealUaEngineLabel() => PrismNative.read(SealedIndex.uaEngineLabel);
String unsealUaEngineTail() => PrismNative.read(SealedIndex.uaEngineTail);
String unsealUaChromeLabel() => PrismNative.read(SealedIndex.uaChromeLabel);
String unsealUaMobileSafari() =>
    PrismNative.read(SealedIndex.uaMobileSafari);
String unsealChromeVersion() => PrismNative.read(SealedIndex.chromeVersion);
String unsealWebkitVersion() => PrismNative.read(SealedIndex.webkitVersion);

String unsealUaAppIdToken() => PrismNative.read(SealedIndex.uaAppIdToken);
String unsealUaAppNameToken() =>
    PrismNative.read(SealedIndex.uaAppNameToken);
String unsealAppNameToken() => PrismNative.read(SealedIndex.appNameToken);

String unsealJsSafeArea() => PrismNative.read(SealedIndex.jsSafeArea);
String unsealJsKeyboard() => PrismNative.read(SealedIndex.jsKeyboard);
String unsealJsAutoplay() => PrismNative.read(SealedIndex.jsAutoplay);
String unsealJsHop() => PrismNative.read(SealedIndex.jsHop);

// `unsealUrlPrivacy` / `unsealUrlSupport` intentionally removed
// — the Rust-guard template keeps those public legal pages on
// the Play Console listing only, so no client-side opener is
// needed and no partner URL ships in the binary.

/// Builds the GCD rescue URL for a given install. Returns `""`
/// when the base or the dev key cannot be resolved so callers
/// treat the rescue as unavailable and keep whatever the AF SDK
/// already delivered.
String unsealGcdCallUrl(String bundleId, String deviceId) {
  final String base = unsealGcdBase();
  if (base.isEmpty) return '';
  final String key = unsealAttributionKey();
  if (key.isEmpty) return '';
  return '$base$bundleId?devkey=$key&device_id=$deviceId';
}

/// `true` once the Rust library has been loaded and both FFI
/// symbols resolved. Not required for correctness — every
/// `unseal*` call already fails open — but useful for health
/// probes.
bool get prismNativeReady => PrismNative.isAvailable;
