<#
  build_rust.ps1 — compile prism_core into libprism_core.so for the
  Android ABIs and drop them into android/app/src/main/jniLibs/<abi>/.

  Windows counterpart of tool/build_rust.sh. Run after any change to
  rust/prism_core (sources OR the sealed arrays regenerated by
  tool/prism_pack.dart):

      pwsh tool/build_rust.ps1

  Dependencies:
    - rustup + cargo
    - cargo-ndk            (cargo install cargo-ndk)
    - rust targets         (rustup target add aarch64-linux-android
                            armv7-linux-androideabi x86_64-linux-android)
    - Android NDK          (resolved from $env:ANDROID_NDK_HOME or the
                            default Android SDK ndk/ folder)
#>
$ErrorActionPreference = 'Stop'

$root     = Split-Path -Parent $PSScriptRoot
$crateDir = Join-Path $root 'rust\prism_core'
$jniDir   = Join-Path $root 'android\app\src\main\jniLibs'

# Resolve the NDK if not already exported.
if (-not $env:ANDROID_NDK_HOME -or -not (Test-Path $env:ANDROID_NDK_HOME)) {
    $sdkNdk = Join-Path $env:LOCALAPPDATA 'Android\Sdk\ndk'
    if (Test-Path $sdkNdk) {
        $latest = Get-ChildItem $sdkNdk -Directory |
            Sort-Object Name -Descending | Select-Object -First 1
        if ($latest) { $env:ANDROID_NDK_HOME = $latest.FullName }
    }
}
if (-not $env:ANDROID_NDK_HOME -or -not (Test-Path $env:ANDROID_NDK_HOME)) {
    Write-Error 'ANDROID_NDK_HOME is not set and no NDK was found under the Android SDK. Install an NDK via Android Studio and re-run.'
}
Write-Host "Using NDK: $env:ANDROID_NDK_HOME"

Push-Location $crateDir
try {
    cargo ndk `
        -t arm64-v8a `
        -t armeabi-v7a `
        -t x86_64 `
        -o $jniDir `
        build --release
    if ($LASTEXITCODE -ne 0) { throw "cargo ndk failed ($LASTEXITCODE)" }
} finally {
    Pop-Location
}

Write-Host "`nBuilt jniLibs:"
Get-ChildItem $jniDir -Recurse -Filter libprism_core.so |
    ForEach-Object { '{0}  {1:N0} bytes' -f $_.Directory.Name, $_.Length }
Write-Host 'prism_core shared libraries updated.'
